%data = load('..\data\phase_p.txt'); DisplayName = 'phase_p';
%data = load('..\data\ellipse.txt'); DisplayName = 'ellipse';
%data = load('..\data\lp.txt'); DisplayName = 'lp';
data = load('..\data\rot_num.txt'); DisplayName = 'rot_num';

hold on
plot(data(:,1), data(:,2), ...
    '.-', ...
    'MarkerSize', 6, ...
    'Color', [77/255 190/255 238/255], ...
    'DisplayName', DisplayName)

legend('off')
